Add Bitcoin Currency German
paralelolab/bitcoindesigned-infographics-i18n pull request #10
Opened 2018-06-25 14:30 UTC by sergebrunner

First translation to German. Thank you!

2018-06-25 14:46 UTC, lclc requested changes

2018-06-25 14:46 UTC, lclc commented on what-is-bitcoin-the-currency/was-ist-bitcoin-die-währung.po
> +msgstr "Dein Name ist nicht mit deinen Transaktionen verlinkt, was bitcoin."
Missing sentence.

2018-06-25 14:46 UTC, lclc commented on what-is-bitcoin-the-currency/was-ist-bitcoin-die-währung.po
> +"Ist eine Bitcointransaktionen bestätigt, kann diese nicht wieder rückgängig "
Bitcointransaktionen -> Bitcointransaktion

2018-06-25 14:46 UTC, lclc commented on what-is-bitcoin-the-currency/was-ist-bitcoin-die-währung.po
> +"zwei Parteien - wie zum Beispiel eine Laden."
" - wie zum Beispiel eine Laden."

Fix Laden or Remove

2018-06-25 14:46 UTC, lclc commented on what-is-bitcoin-the-currency/was-ist-bitcoin-die-währung.po
> +msgstr "Transaktionen können jeden überall in der Welt in Minuten erreichen."
maybe

> innerhalb von Minuten erreichen.

2018-06-25 14:46 UTC, lclc commented on what-is-bitcoin-the-currency/was-ist-bitcoin-die-währung.po
> +"Falls das Transaktionsvolumen stark ansteigt - wenn Bitcoin Mainstream wird "
> wenn Bitcoin Mainstream wird 

> etwa wenn Bitcoin Mainstream wird

2018-06-25 14:46 UTC, lclc commented on what-is-bitcoin-the-currency/was-ist-bitcoin-die-währung.po
> +"lange auf die Bestätigung."
add

> warten möchtest.

2018-06-26 10:37 UTC, merged

2018-06-26 10:38 UTC, patestevao commented
Thank you, @sergebrunner and @lclc! It is now merged and will soon be online. :)